server:
  port: 8002

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.38:3306/edu?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: edu
    password: edu
    min-idle: 50
    initial-size: 20
    max-total: 50
    max-wait-millis: 200

mybatis-plus:
  mapper-locations:
    - classpath:./mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml